### ISSUE TITLE
403 from Binance scraper

### ISSUE THREAD

**Issue by zilvester** [CyberPunkMetalHead/gateio-crypto-trading-bot-binance-announcements-new-coins#151] opened 2022-01-16 13:15 UTC
https://www.binancezh.com/gateway-api/v1/public/cms/article/list/query?type=1&catalogid=48

I'm guessing this has happened only very recently... :(

**Comment by Linus045** [comment] 2022-01-16 14:08
This is a duplicate of #137 therefore i will close this issue.

**Closed by Linus045** 2022-01-16 14:08 UTC
Labels: duplicate
